/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thegameoflife;

import java.awt.Color;
import java.awt.Graphics;
import static thegameoflife.TheGameOfLife.grid;

/**
 *
 * @author Greg
 */
public class GameOfLifePanel extends javax.swing.JPanel {

    /**
     * Creates new form GameOfLifePanel
     */
    
    TheGameOfLife game = new TheGameOfLife();
    
    public GameOfLifePanel() {
        initComponents();
        grid[2][2] = true;
        grid[3][2] = true;
        grid[4][2] = true;
    }

    public void paintComponent(Graphics g) {
        int x = 0;
        int y = 0;
        //TheGameOfLife.grid[0][0];
        for (int c = 0; c < grid.length; c++) {
            for (int r = 0; r < grid[0].length; r++) {
                if (grid[c][r]) {
                    g.setColor(Color.white);
                } else {
                    g.setColor(Color.black);
                }
                g.fillRect(x, y, 7, 5);
                x += 7;

            }
            x = 0;
            y += 7;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
